# Watch-Dog Protocol Schema
# 定義 config.yaml 的結構與驗證規則

# ============================================================
# 專案基本資訊 (必填)
# ============================================================
project:
  name:                    # string, required: 專案識別名稱 (英文, snake_case)
  display_name:            # string, required: 顯示名稱
  base_url:                # string, required: 生產環境 URL
  staging_url:             # string, optional: Staging 環境 URL

# ============================================================
# 檢查項目定義 (必填，至少一項)
# ============================================================
checks:
  - name:                  # string, required: 檢查項目唯一識別碼
    display_name:          # string, required: 顯示名稱
    script:                # string, required: 檢查腳本路徑 (相對於 config.yaml)
    schedule:              # string, required: Crontab 格式 "分 時 日 月 週"
    timeout:               # integer, required: 執行逾時秒數
    enabled:               # boolean, default: true
    retry:                 # integer, default: 0: 失敗重試次數
    retry_delay:           # integer, default: 30: 重試間隔秒數

# ============================================================
# 警報設定 (可選)
# ============================================================
alerts:
  slack:
    enabled:               # boolean, default: false
    webhook_url:           # string, optional: (優先於 token)
    bot_token:             # string, optional
    channel:               # string, required if enabled
    on_failure:            # boolean, default: true
    on_recovery:           # boolean, default: true
    on_start:              # boolean, default: false

  email:
    enabled:               # boolean, default: false
    recipients:            # list of string, required if enabled

  # 可擴充: discord, telegram, line...

# ============================================================
# 狀態管理 (可選)
# ============================================================
status:
  file:                    # string, default: ".test-status.json"
  sync_to_project:         # boolean, default: true: 是否同步回原專案

# ============================================================
# 專案路徑 (必填)
# ============================================================
paths:
  project_root:            # string, required: 專案絕對路徑
  log_dir:                 # string, optional: 日誌輸出目錄
  work_dir:                # string, optional: 執行時工作目錄

# ============================================================
# 閾值設定 (可選)
# ============================================================
thresholds:
  breadcrumb_match:        # integer, default: 70, 百分比
  seo_score:               # integer, default: 70, 百分比
  response_time:           # integer, default: 5000, 毫秒

# ============================================================
# 範例
# ============================================================
# project:
#   name: "topreview_edge"
#   display_name: "TopReview Edge"
#   base_url: "https://topreview.cc"
#
# checks:
#   - name: "smoke"
#     display_name: "Smoke Test"
#     script: "checks/smoke.py"
#     schedule: "0 2 * * *"
#     timeout: 180
#
# paths:
#   project_root: "/home/peterpai/work/topreview-edge"
